### ISSUE TITLE
Django@3.1 support

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/django-test-migrations#117]
New LTS version is out!

**Comment by mchels** [comment]
I have run into https://code.djangoproject.com/ticket/31477 which gives an error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/contrib/unittest_case.py", line 36, in setUp
    self.migrate_from,
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/migrator.py", line 46, in apply_initial_migration
    sql.drop_models_tables(self._database, style)
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/sql.py", line 32, in drop_models_tables
    get_execute_sql_flush_for(connection)(database_name, sql_drop_tables)
TypeError: execute_sql_flush() takes 2 positional arguments but 3 were given
```
It's also in the django 3.1 release notes: https://docs.djangoproject.com/en/3.1/releases/3.1/#backwards-incompatible-changes-in-3-1. Potentially the fix is simply to remove this line
https://github.com/wemake-services/django-test-migrations/blob/d35f4b1c6e6ddead914390368190d0dd6444d9cb/django_test_migrations/sql.py#L54
and remove `database_name` from 
https://github.com/wemake-services/django-test-migrations/blob/master/django_test_migrations/sql.py#L32
but I am not sure.

I am also hitting
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/contrib/unittest_case.py", line 36, in setUp
    self.migrate_from,
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/migrator.py", line 47, in apply_initial_migration
    sql.flush_django_migrations_table(self._database, style)
  File "/usr/local/lib/python3.7/site-packages/django_test_migrations/sql.py", line 60, in flush_django_migrations_table
    allow_cascade=False,
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/operations.py", line 130, in sql_flush
    style.SQL_KEYWORD('TRUNCATE'),
AttributeError: 'list' object has no attribute 'SQL_KEYWORD'
```
probably because the signature for `sql_flush` has changed (also in https://docs.djangoproject.com/en/3.1/releases/3.1/#backwards-incompatible-changes-in-3-1). Compare
https://github.com/django/django/blob/3.0.9/django/db/backends/base/operations.py#L384
vs
https://github.com/django/django/blob/3.1/django/db/backends/base/operations.py#L392
I am not sure how to handle this one.

**Comment by skarzi** [comment]
@mchels  thank you for the report! :+1: 
I will investigate it whenever I find some time and prepare PR with fixes

**Comment by mijamo** [comment]
Would it be possible to push a release with the new Django version support reasonably soon? This is actually the only dependency blocking me from updating a Django project right now.

**Comment by mschoettle** [comment]
Can you please release a new version to have Django 3.1 support?

**Comment by jamesd-vg** [comment]
Has there been any movement on this? Currently the only thing holding us back from Django 3.1

**Comment by skarzi** [comment]
Django 3.1 support was added to the project in #123 and it's already present on `master` (see [last `test` workflow run](https://github.com/wemake-services/django-test-migrations/actions/runs/390198392)), but we need to release a new version of our package. Currently, I'm testing `master` branch on a few bigger projects to be sure it works correctly

**Comment by jamesd-vg** [comment]
@skarzi great news! Thankyou

**Comment by mschoettle** [comment]
For those on here that missed the release: v1.1.0 with Django 3.1 support was released.
