### ISSUE TITLE
Import pre-migration data from an SQL file

### ISSUE THREAD

**Issue by vesnikos** [wemake-services/django-test-migrations#81]
Hi, is it possible to use an sql extract to test the migration procedure? ie

```python 
class TestDirectMigration(MigratorTestCase,_TestUtils):
    """This class is used to test direct migrations."""
    migrate_from = ('app', '0016_auto_20200416_1527')
    migrate_to = ('app', '0017_auto_20200511_1641')

    def prepare(self):
        """Prepare some data before the migration."""
        test_data = self.resource_path('migration_test_data/0016_auto_20200416_1527.sql')
        with connection.cursor() as cursor:
            for l in test_data.read_text().strip().split(';'):
                cursor.execute(l)
```

**Comment by skarzi** [comment]
Hello @vesnikos

What do you mean by "sql extract"?  SQL `EXTRACT` function or just executing some raw SQL queries?
Generally you can do whatever you want in `.prepare()` to setup some test data for instance, you can execute raw SQL queries like in your example

**Comment by vesnikos** [comment]
HI @skarzi , 

Yes, sorry. by `extract` I was refering to a partial data-only dump from the database before any migrations. That .sql file over there, was just containing a bunch of import statments generated from our live database. 

If that's the case and could be done, it would be great there was a reference of such use case in the documentation.

Using file-fixtures to populate the table makes sense if you have multiple tables and inputing mock data is cumbersome.  For that case django already supports test fixtures, but now as I write this, I am kinda confused: in which state a test-fixture would be applied at? surely it should be the before-state right?

**Comment by skarzi** [comment]
> For that case django already supports test fixtures, but now as I write this, I am kinda confused: in which state a test-fixture would be applied at? surely it should be the before-state right?

It should be applied **after** calling `.before()`([example](https://github.com/wemake-services/django-test-migrations/blob/a7aeb32c0309348d7e1eb63b5b92f8627f8338ce/tests/test_contrib/test_pytest_plugin/test_pytest_plugin_direct.py#L45)) or inside `.prepare()` when using unittest testcase ([example](https://github.com/wemake-services/django-test-migrations/blob/a7aeb32c0309348d7e1eb63b5b92f8627f8338ce/tests/test_contrib/test_unittest_case/test_unittest_case.py#L12)), because `.before()` goal is to prepare database state without migration that is being tested applied, so you can populate all necessary data to test this migration.

Generally you can do whatever you want there, even load execute some raw SQL queries, however please remember that tables scheme can change, so you will have to version somehow your SQL files and solve some other challenges related to maintaining SQL files.
